/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

/**
 *
 * @author 1
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nmPrincipal = new javax.swing.JMenuBar();
        mnPrinCadastros = new javax.swing.JMenu();
        mnPrinCadUsers = new javax.swing.JMenuItem();
        mnPrinCadPermissoes = new javax.swing.JMenuItem();
        mnPrinSair = new javax.swing.JMenu();
        mnPrinSairExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Um");
        setResizable(false);

        mnPrinCadastros.setText("Cadastros");
        mnPrinCadastros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPrinCadastrosActionPerformed(evt);
            }
        });

        mnPrinCadUsers.setText("Cadastro de Usuários");
        mnPrinCadUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPrinCadUsersActionPerformed(evt);
            }
        });
        mnPrinCadastros.add(mnPrinCadUsers);

        mnPrinCadPermissoes.setText("Cadastro de Permissoes");
        mnPrinCadPermissoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPrinCadPermissoesActionPerformed(evt);
            }
        });
        mnPrinCadastros.add(mnPrinCadPermissoes);

        nmPrincipal.add(mnPrinCadastros);

        mnPrinSair.setText("Sair");
        mnPrinSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPrinSairActionPerformed(evt);
            }
        });

        mnPrinSairExit.setText("Exit");
        mnPrinSairExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPrinSairExitActionPerformed(evt);
            }
        });
        mnPrinSair.add(mnPrinSairExit);

        nmPrincipal.add(mnPrinSair);

        setJMenuBar(nmPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 602, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(618, 411));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnPrinSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPrinSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnPrinSairActionPerformed

    private void mnPrinSairExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPrinSairExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnPrinSairExitActionPerformed

    private void mnPrinCadastrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPrinCadastrosActionPerformed

        
    }//GEN-LAST:event_mnPrinCadastrosActionPerformed

    private void mnPrinCadUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPrinCadUsersActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        TelaCadUsers tlCadUsers = new TelaCadUsers();
        // Tornando a TelaPrincipal visível
        tlCadUsers.setVisible(true);
        // Fechando a TelaLogin        
    }//GEN-LAST:event_mnPrinCadUsersActionPerformed

    private void mnPrinCadPermissoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPrinCadPermissoesActionPerformed
        // TODO add your handling code here:
        TelaCadPermissoes tlCadPermis = new TelaCadPermissoes();
        // Tornando a TelaPrincipal visível
        tlCadPermis.setVisible(true);        
        
    }//GEN-LAST:event_mnPrinCadPermissoesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem mnPrinCadPermissoes;
    private javax.swing.JMenuItem mnPrinCadUsers;
    private javax.swing.JMenu mnPrinCadastros;
    private javax.swing.JMenu mnPrinSair;
    private javax.swing.JMenuItem mnPrinSairExit;
    private javax.swing.JMenuBar nmPrincipal;
    // End of variables declaration//GEN-END:variables
}
