package Telas;

// Passo 1; Importar os módulos e blibliotecas
import DataAccess.ModuloDbConnect;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class TelaCadPermissoes extends javax.swing.JFrame {

    // Passo 2 - Definir as variaveis auxiliares para a conexão
    Connection conexao = null; // retorna o status da conexão
    PreparedStatement pst = null; // Coloca o comando SQL na conexão do banco
    ResultSet rs = null; // Retornar o resultado do comando executado no banco
        
    public TelaCadPermissoes() {
        initComponents();
        // Passo 3 - Estabelecer/executar a conexão com o banco
        conexao = ModuloDbConnect.connector();
        // Testando o resultado  da conexao
        if (conexao != null) {
            System.out.println("String da conexao Ok: " + conexao);
            lblStatusDB.setText("Conectado OK!");
            lblStatusDB.setForeground(Color.blue);
        }else {
            lblStatusDB.setText("NÃO Conectado.");
            lblStatusDB.setForeground(Color.red);
            }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStatusDB = new javax.swing.JLabel();
        btnFecharPermissoes = new javax.swing.JButton();
        txtIdPer = new javax.swing.JTextField();
        txtCodPerm = new javax.swing.JTextField();
        txtNivelPerm = new javax.swing.JTextField();
        txtCargo = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        btnIncluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        idlbPerm = new javax.swing.JLabel();
        lblCdPerm = new javax.swing.JLabel();
        lblNivelPerm = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        BtnLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Permissões");
        setResizable(false);

        lblStatusDB.setText("Nao Conectado");

        btnFecharPermissoes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnFecharPermissoes.setText("Fechar");
        btnFecharPermissoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharPermissoesActionPerformed(evt);
            }
        });

        txtCodPerm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodPermActionPerformed(evt);
            }
        });

        btnConsultar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnIncluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnIncluir.setText("Incluir");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        btnAlterar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        idlbPerm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        idlbPerm.setText("ID");

        lblCdPerm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCdPerm.setText("Codigo da permissão");

        lblNivelPerm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNivelPerm.setText("Nivel Permissão");

        lblCargo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCargo.setText("Cargo");

        BtnLimpar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnLimpar.setText("Limpar");
        BtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatusDB, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnConsultar)
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnFecharPermissoes)
                                .addGap(42, 42, 42)
                                .addComponent(BtnLimpar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnIncluir)
                                .addGap(53, 53, 53)
                                .addComponent(btnAlterar)
                                .addGap(57, 57, 57)
                                .addComponent(btnExcluir)))))
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNivelPerm)
                            .addComponent(lblCargo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNivelPerm)
                            .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(idlbPerm)
                            .addComponent(lblCdPerm))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdPer, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodPerm, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idlbPerm)
                    .addComponent(txtIdPer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCdPerm)
                    .addComponent(txtCodPerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNivelPerm)
                    .addComponent(txtNivelPerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCargo)
                    .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(btnIncluir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFecharPermissoes)
                    .addComponent(BtnLimpar))
                .addGap(5, 5, 5)
                .addComponent(lblStatusDB)
                .addGap(16, 16, 16))
        );

        setSize(new java.awt.Dimension(546, 435));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharPermissoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharPermissoesActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnFecharPermissoesActionPerformed

    private void txtCodPermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodPermActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodPermActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
        // Criando a variavel para o comando SQL de consulta
        String sql = "select * from tbnivelper where idTbNivelperPK = ?";

        // Definir o comando de acesso ao banco: try/catch
        try {
            // Associar o comando SQL na conexao ao Banco
            pst = conexao.prepareStatement(sql);
            // Passando a informação do campo usuario da Tela para o 1o. parametro
            // do comando SQL acima.
            pst.setString(1,txtIdPer.getText());
            // Executar/rodar a consulta/comando no banco de dados
            rs = pst.executeQuery();

            // Testar o sucesso da consulta !!!!
            if  (rs.next()) {
                // SUCESSO !!! Encontrou a consulta Ok
                // Preencher/Escrever as informaçoes consultadas na Tela
                txtIdPer.setText(rs.getString(1));
                txtCodPerm.setText(rs.getString(2));
                txtNivelPerm.setText(rs.getString(3));
                txtCargo.setText(rs.getString(4));

            } else {
                // Erro na Consulta!!!
                JOptionPane.showMessageDialog(null, "ID / Cadastro INVÁLIDO !!!");
                // Limpando os campos da Tela!
                txtIdPer.setText("");
                txtCodPerm.setText("");
                txtNivelPerm.setText("");
                txtCargo.setText("");
            }

        }catch (Exception varERRO) {
            JOptionPane.showMessageDialog(null, "Erro no acesso ao Banco DbLogin - Cad. Usuario: " + varERRO.toString());
        }

    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        // TODO add your handling code here:
        String sql = "insert into tbnivelper(idTbNivelperPK,cdNivelPer,dsNivelPer,DsCargo) VALUES (?, ?, ?, ?)";

            try {
                // Colocar o comando SQL, acima, na conexão do banco
                pst = conexao.prepareStatement(sql);
                // Colocar os campos da tela no comando da conexão ao banco
                pst.setString(1, txtIdPer.getText());
                pst.setString(2, txtCodPerm.getText());
                pst.setString(3, txtNivelPerm.getText());
                pst.setString(4, txtCargo.getText());
                
                // Executamos o comando sql de inserção com o "executeUpdate"
                int adicionado = 0;
                adicionado = pst.executeUpdate();
                if (adicionado > 0) {
                    JOptionPane.showMessageDialog(null, "Inclusão OK!!");
                    txtIdPer.setText(" ");
                    txtCodPerm.setText(" ");
                    txtNivelPerm.setText(" ");
                    txtCargo.setText(" ");
                    
                } else {
                    JOptionPane.showMessageDialog(null, "Usuário já cadastrado");
                }
            } catch (Exception varERRO) {
                JOptionPane.showMessageDialog(null, "Usuário Adicionado com Sucesso - Erro na rotina de inclusao: " + varERRO.toString());
            }
        

    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        String sql = "UPDATE tbnivelper SET idTbNivelperPK = ?, cdNivelPer = ?,dsNivelPer = ?, DsCargo = ? WHERE  idTbNivelperPK = ?";

        try {
            // Colocar o comando SQL, acima, na conexão do banco
            pst = conexao.prepareStatement(sql);
            // Colocar os campos da tela no comando da conexão ao banco
            pst.setString(1, txtIdPer.getText());
            pst.setString(2, txtCodPerm.getText());
            pst.setString(3, txtNivelPerm.getText());
            pst.setString(4, txtCargo.getText());
            pst.setString(5, txtIdPer.getText());
            // Executamos o comando sql de alteração/UPDATE com o "executeUpdate"

            int alterado = 0;
            alterado = pst.executeUpdate();
            if (alterado > 0) {
                JOptionPane.showMessageDialog(null, "Alterado OK!!");
                txtIdPer.setText(" ");
                txtCodPerm.setText(" ");
                txtNivelPerm.setText(" ");
                txtCargo.setText(" ");
            } else {
                JOptionPane.showMessageDialog(null, "Usuário Inexistente");
            }
        } catch (Exception varERRO) {
            JOptionPane.showMessageDialog(null, "Usuário Alterado com Sucesso - Erro na rotina de inclusao: " + varERRO.toString());
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // Confirmar para a exclusão perguntando o usuário se ele confirma
        int confirmaOK = JOptionPane.showConfirmDialog(null, "Confirma a exclusão do registro?", "ATENÇÃO", JOptionPane.YES_NO_OPTION);

        if (confirmaOK == JOptionPane.YES_OPTION) {
            // Constroi o comando SQL de deleção
            String sql = "DELETE FROM tbnivelper WHERE idTbNivelperPK = ?";
            try {
                pst = conexao.prepareStatement(sql);
                // Colocar os campos da tela no comando da conexão ao banco
                pst.setString(1, txtIdPer.getText());
                // Executando a deleção do registro
                pst.executeUpdate();

            } catch (Exception varERRO){
                JOptionPane.showMessageDialog(null, "Erro na rotina de exclusão");
            }
    }//GEN-LAST:event_btnExcluirActionPerformed
    }
    private void BtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimparActionPerformed
        txtIdPer.setText(" ");
        txtCodPerm.setText(" ");
        txtNivelPerm.setText(" ");
        txtCargo.setText(" ");
    }//GEN-LAST:event_BtnLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadPermissoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadPermissoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadPermissoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadPermissoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadPermissoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLimpar;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFecharPermissoes;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JLabel idlbPerm;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblCdPerm;
    private javax.swing.JLabel lblNivelPerm;
    private javax.swing.JLabel lblStatusDB;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtCodPerm;
    private javax.swing.JTextField txtIdPer;
    private javax.swing.JTextField txtNivelPerm;
    // End of variables declaration//GEN-END:variables
}
